export let data=[
    {
        "id": 1,
        "videoTime": "14:20",
        "youtubeLink": "https://www.youtube.com/watch?v=n2RNcPRtAiY",
        "thumbnail": "images/thumbnail-1.webp",
        "channelLink": "https://www.youtube.com/c/mkbhd",
        "channelPhoto": "images/channel-1.jpeg",
        "channelTitle": "Marques Brownlee",
        "subscribers": "17.7M subscribers",
        "videoTitle": "Talking Tech and AI with Google CEO Sundar Pichai!",
        "videoViews": "3.4M views · 6 months ago"
    },
    {
        "id": 2,
        "videoTime": "8:22",
        "youtubeLink": "https://www.youtube.com/watch?v=mP0RAo9SKZk",
        "thumbnail": "images/thumbnail-2.webp",
        "channelLink": "https://www.youtube.com/c/markiplier",
        "channelPhoto": "images/channel-2.jpeg",
        "channelTitle": "Markiplier",
        "subscribers": "35.6M subscribers",
        "videoTitle": "Try Not To Laugh Challenge #9",
        "videoViews": "19M views · 4 years ago"
    },
    {
        "id": 3,
        "videoTime": "9:13",
        "youtubeLink": "https://www.youtube.com/watch?v=FgjPQQeTh1w",
        "thumbnail": "images/thumbnail-3.webp",
        "channelLink": "https://www.youtube.com/user/SSSniperWolf",
        "channelPhoto": "images/channel-3.jpeg",
        "channelTitle": "SSSniperWolf",
        "subscribers": "34.2M subscribers",
        "videoTitle": "Crazy Tik Toks Taken Moments Before DISASTER",
        "videoViews": "12M views · 1 year ago"
    },
    {
        "id": 4,
        "videoTime": "22:09",
        "youtubeLink": "https://www.youtube.com/watch?v=094y1Z2wpJg",
        "thumbnail": "images/thumbnail-4.webp",
        "channelLink": "https://www.youtube.com/c/veritasium",
        "channelPhoto": "images/channel-4.jpeg",
        "channelTitle": "Veritasium",
        "subscribers": "14.3M subscribers",
        "videoTitle": "The Simplest Math Problem No One Can Solve - Collatz Conjecture",
        "videoViews": "18M views · 4 months ago"
    },
    {
        "id": 5,
        "videoTime": "11:17",
        "youtubeLink": "https://www.youtube.com/watch?v=86CQq3pKSUw",
        "thumbnail": "images/thumbnail-5.webp",
        "channelLink": "https://www.youtube.com/c/CSDojo",
        "channelPhoto": "images/channel-5.jpeg",
        "channelTitle": "CS Dojo",
        "subscribers": "1.92M subscribers",
        "videoTitle": "Kadane's Algorithm to Maximum Sum Subarray Problem",
        "videoViews": "519K views · 5 years ago"
    },
    {
        "id": 6,
        "videoTime": "19:59",
        "youtubeLink": "https://www.youtube.com/watch?v=yXWw0_UfSFg",
        "thumbnail": "images/thumbnail-6.webp",
        "channelLink": "https://www.youtube.com/channel/UCX6OQ3DkcsbYNE6H8uQQuVA",
        "channelPhoto": "images/channel-6.jpeg",
        "channelTitle": "MrBeast",
        "subscribers": "200M subscribers",
        "videoTitle": "Anything You Can Fit In The Circle I’ll Pay For",
        "videoViews": "141M views · 1 year ago"
    },
    {
        "id": 7,
        "videoTime": "10:13",
        "youtubeLink": "https://www.youtube.com/watch?v=fNVa1qMbF9Y",
        "thumbnail": "images/thumbnail-7.webp",
        "channelLink": "https://www.youtube.com/channel/UCP5tjEmvPItGyLhmjdwP7Ww",
        "channelPhoto": "images/channel-7.jpeg",
        "channelTitle": "RealLifeLore",
        "subscribers": "7.15M subscribers",
        "videoTitle": "Why Planes Don't Fly Over Tibet",
        "videoViews": "6.6M views · 1 year ago"
    },
    {
        "id": 8,
        "videoTime": "7:12",
        "youtubeLink": "https://www.youtube.com/watch?v=lFm4EM1juls",
        "thumbnail": "images/thumbnail-8.webp",
        "channelLink": "https://www.youtube.com/channel/UCHAK6CyegY22Zj2GWrcaIxg",
        "channelPhoto": "images/channel-8.jpeg",
        "channelTitle": "Tech Vision",
        "subscribers": "820K subscribers",
        "videoTitle": "Inside The World's Biggest Passenger Plane",
        "videoViews": "3.7M views · 10 months ago"
    },
    {
        "id": 9,
        "videoTime": "13:17",
        "youtubeLink": "https://www.youtube.com/watch?v=ixmxOlcrlUc",
        "thumbnail": "images/thumbnail-9.webp",
        "channelLink": "https://www.youtube.com/c/OFFICIALTHENXSTUDIOS",
        "channelPhoto": "images/channel-9.jpeg",
        "channelTitle": "ThenX",
        "subscribers": "7.7M subscribers",
        "videoTitle": "The SECRET to Super Human STRENGTH",
        "videoViews": "20M views · 3 year ago"
    },
    {
        "id": 10,
        "videoTime": "7:53",
        "youtubeLink": "https://www.youtube.com/watch?v=R2vXbFp5C9o",
        "thumbnail": "images/thumbnail-10.webp",
        "channelLink": "https://www.youtube.com/user/businessinsider",
        "channelPhoto": "images/channel-10.jpeg",
        "channelTitle": "Business Insider",
        "subscribers": "8.38M subscribers",
        "videoTitle": "How The World's Largest Cruise Ship Makes 30,000 Meals Every Day",
        "videoViews": "14M views · 1 year ago"
    },
    {
        "id": 11,
        "videoTime": "4:10",
        "youtubeLink": "https://www.youtube.com/watch?v=0nZuYyXET3s",
        "thumbnail": "images/thumbnail-11.webp",
        "channelLink": "https://www.youtube.com/c/Destinationtips",
        "channelPhoto": "images/channel-11.jpeg",
        "channelTitle": "Destination Tips",
        "subscribers": "282K subscribers",
        "videoTitle": "Dubai's Crazy Underwater Train and Other Things #Only in Dubai",
        "videoViews": "3M views · 1 year ago"
    },
    {
        "id": 12,
        "videoTime": "4:51",
        "youtubeLink": "https://www.youtube.com/watch?v=9iMGFqMmUFs",
        "thumbnail": "images/thumbnail-12.webp",
        "channelLink": "https://www.youtube.com/teded",
        "channelPhoto": "images/channel-12.jpeg",
        "channelTitle": "TED-Ed",
        "subscribers": "19.1M subscribers",
        "videoTitle": "What would happen if you didn’t drink water? - Mia Nacamulli",
        "videoViews": "12M views · 5 years ago"
    }
]